[dependencies]
base = "0.9.4"
xtended-text = "0.2.5"

[package]
name = "datetime"
version = "0.1.3"
description = "A library for DateTime values and manipulation in Motoko"
repository = "https://github.com/edjcase/motoko_datetime"

[dev-dependencies]
test = "1.0.1"
