[dependencies]
base = "0.8.3"

[package]
name = "DateTime"
version = "0.1.0"
description = "A library for DateTime manipulation in Motoko"
repository = "https://github.com/edjcase/motoko_datetime"

[dev-dependencies]
test = "1.0.1"