[package]
name = "datetime"
version = "1.0.0"
description = "A library for DateTime values and manipulation in Motoko"
repository = "https://github.com/edjcase/motoko_datetime"
keywords = [ "datetime", "time", "date", "timezone" ]
license = "MIT"

[dependencies]
core = "0.6.0"
xtended-text = "2.0.0"

[dev-dependencies]
test = "2.1.1"
